import React from 'react'
import {connect} from 'react-redux'
import {authenticate} from '../store'
import { View, TextInput, Text } from 'react-native'

import React from 'react'
import {connect} from 'react-redux'
import {authenticate} from '../store'

// import this into app to render first 

//creating class component with stateful form handling ents to be the thing automatically generated by text input
//will need to change ev

class AuthForm extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      username = '',
      password = ''
    }
  }
}

const AuthForm = props => {
  const {name, displayName, handleSubmit, error} = props

  return (
    <View>
        <Text>Username</Text>
        <TextInput></TextInput>

        <Text>Password</Text>
        <TextInput></TextInput>
      
    </View>


      {/* <form onSubmit={handleSubmit} name={name}>
        <div>
          <label htmlFor="username">
            <small>Username</small>
          </label>
          <input name="username" type="text" />
        </div>
        <div>
          <label htmlFor="password">
            <small>Password</small>
          </label>
          <input name="password" type="password" />
        </div>
        <div>
          <button type="submit">{displayName}</button>
        </div>
        {error && error.response && <div> {error.response.data} </div>}
      </form> */}
    
  )
}


const mapLogin = state => {
  return {
    name: 'login',
    displayName: 'Login',
    error: state.auth.error
  }
}

const mapSignup = state => {
  return {
    name: 'signup',
    displayName: 'Sign Up',
    error: state.auth.error
  }
}

const mapDispatch = dispatch => {
  return {
    handleSubmit(evt) {
      evt.preventDefault()
      const formName = evt.target.name
      const username = evt.target.username.value
      const password = evt.target.password.value
      dispatch(authenticate(username, password, formName))
    }
  }
}

export const Login = connect(mapLogin, mapDispatch)(AuthForm)
export const Signup = connect(mapSignup, mapDispatch)(AuthForm)

